apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  name: m2kenterprise-clone-build-push-orders
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: quay.io/jobinl400ey/orders:latest
    pushSecret:
      name: dockerquay
  postCommit: {}
  resources: {}
  source:
    git:
      ref: main
      uri: https://github.com/Jobinl400EY/m2kenterprise
    sourceSecret:
      name: m2kenterprise-git-repo-generic
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: source/orders/Dockerfile
    type: Docker
  triggers:
    - generic:
        secretReference:
          name: m2kenterprise-web-hook-orders
      type: Generic
status:
  lastVersion: 0
