apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  name: m2kenterprise-clone-build-push-orders
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: orders-latest:latest
  postCommit: {}
  resources: {}
  source:
    git:
      ref: main
      uri: ""
    sourceSecret:
      name: m2kenterprise-git-repo-generic
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: '<TODO: insert path to the Dockerfile>'
    type: Docker
  triggers:
    - generic:
        secretReference:
          name: m2kenterprise-web-hook-orders
      type: Generic
status:
  lastVersion: 0
